### PR TITLE
Add Carbon Unique EasterEgg

### PR DESCRIPTION
**Pull request by Myself5**
Please test, share opinion and merge ;)

### CODE REVIEW

**Comment by ateek-ujjawal** [comment]
I think google used vector xml in their code, to write that "Lollipop" inside the lollipop(See the file path core/res/res/drawable-nodpi/cm_platlogo.xml)
I don't think this will work, but who knows. :D

**Comment by STELIX** [comment]
About it: works, for sure. About it: already view... maybe we need something new? I would suggest Chris to take a look to CM code used (to inline our Carbon easter egg) and to keep custom puppet into the easter egg game...

**Comment by ateek-ujjawal** [comment]
Works!! Awesome!

**Comment by Myself5** [comment]
who ever said it doesn't :P ?

**Pull request merged**
